### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by nothingneko** [tau-OS/victrola#25]
### What Happened?

jaiden on meowmachine victrola/_build on  main via C v13.2.1-gcc 
❯ sudo ninja install
[3/16] Compiling Vala source ../src/application.vala ../src/main.vala ../src/window.vala ../src/Utils/async-task.vala..../src/Utils/tag-parser.vala ../src/Widgets/info-page.vala ../src/Widgets/play-bar.vala ../src/Widgets/song-entry.vala
FAILED: com.fyralabs.Victrola.p/src/application.c com.fyralabs.Victrola.p/src/main.c com.fyralabs.Victrola.p/src/window.c com.fyralabs.Victrola.p/src/Utils/async-task.c com.fyralabs.Victrola.p/src/Utils/gst-player.c com.fyralabs.Victrola.p/src/Utils/mpris.c com.fyralabs.Victrola.p/src/Utils/song-store.c com.fyralabs.Victrola.p/src/Utils/tag-parser.c com.fyralabs.Victrola.p/src/Widgets/info-page.c com.fyralabs.Victrola.p/src/Widgets/play-bar.c com.fyralabs.Victrola.p/src/Widgets/song-entry.c 
valac -C --debug --debug --gresourcesdir /home/jaiden/Documents/Projects/victrola/_build/data --define=HAS_TAGLIB_C --pkg taglib_c --pkg libbismuth-1 --pkg libhelium-1 --pkg gee-0.8 --pkg gtk4 --pkg gstreamer-tag-1.0 --pkg gstreamer-1.0 --color=always --directory com.fyralabs.Victrola.p --basedir ../ --gresources=../data/app.gresource.xml /home/jaiden/Documents/Projects/victrola/src/Utils/config.vapi /home/jaiden/Documents/Projects/victrola/src/Utils/gst-ext.vapi ../src/application.vala ../src/main.vala ../src/window.vala ../src/Utils/async-task.vala ../src/Utils/gst-player.vala ../src/Utils/mpris.vala ../src/Utils/song-store.vala ../src/Utils/tag-parser.vala ../src/Widgets/info-page.vala ../src/Widgets/play-bar.vala ../src/Widgets/song-entry.vala
../src/window.vala:107.35-107.55: warning: `Gtk.FileChooserNative' has been deprecated since 4.10
  107 |                 var chooser = new Gtk.FileChooserNative (null, this,
      |                                   ^~~~~~~~~~~~~~~~~~~~~             
../src/window.vala:107.21-107.27: warning: `Gtk.FileChooserNative' has been deprecated since 4.10
  107 |                 var chooser = new Gtk.FileChooserNative (null, this,
      |                     ^~~~~~~                                         
../src/window.vala:140.17-140.26: error: The name `child' does not exist in the context of `GLib.Object' (gobject-2.0)
  140 |                 item.child = new SongEntry ();
      |                 ^~~~~~~~~~                    
../src/window.vala:139.37-139.40: note: `item' was declared here
  139 |             factory.setup.connect ((item) => {
      |                                     ^~~~      
../src/window.vala:142.35-142.46: error: Argument 1: Cannot convert from `async void Victrola.MainWindow.on_bind_item (Gtk.ListItem)' to `delegate void Gtk.SignalListItemFactory.bind (Gtk.SignalListItemFactory, GLib.Object)'
  142 |             factory.bind.connect (on_bind_item);
      |                                   ^~~~~~~~~~~~  
../src/window.vala:155.17-155.26: error: The name `child' does not exist in the context of `GLib.Object' (gobject-2.0)
  155 |                 item.child = new SongEntry ();
      |                 ^~~~~~~~~~                    
../src/window.vala:154.38-154.41: note: `item' was declared here
  154 |             factory2.setup.connect ((item) => {
      |                                      ^~~~      
../src/window.vala:157.36-157.47: error: Argument 1: Cannot convert from `async void Victrola.MainWindow.on_bind_item (Gtk.ListItem)' to `delegate void Gtk.SignalListItemFactory.bind (Gtk.SignalListItemFactory, GLib.Object)'
  157 |             factory2.bind.connect (on_bind_item);
      |                                    ^~~~~~~~~~~~  
../src/window.vala:170.17-170.26: error: The name `child' does not exist in the context of `GLib.Object' (gobject-2.0)
  170 |                 item.child = new SongEntry ();
      |                 ^~~~~~~~~~                    
../src/window.vala:169.38-169.41: note: `item' was declared here
  169 |             factory3.setup.connect ((item) => {
      |                                      ^~~~      
../src/window.vala:172.36-172.47: error: Argument 1: Cannot convert from `async void Victrola.MainWindow.on_bind_item (Gtk.ListItem)' to `delegate void Gtk.SignalListItemFactory.bind (Gtk.SignalListItemFactory, GLib.Object)'
  172 |             factory3.bind.connect (on_bind_item);
      |                                    ^~~~~~~~~~~~  
Compilation failed: 6 error(s), 2 warning(s)
ninja: build stopped: subcommand failed.

jaiden on meowmachine victrola/_build on  main via C v13.2.1-gcc 
❯ 

### Steps to Reproduce

Build it

### Expected Behavior

It builds

### OS Version

Ultramarine Linux

### Software Version

Compiled from git

### Log Output

```shell
jaiden on meowmachine victrola/_build on  main via C v13.2.1-gcc 
❯ sudo ninja install
[3/16] Compiling Vala source ../src/application.vala ../src/main.vala ../src/window.vala ../src/Utils/async-task.vala..../src/Utils/tag-parser.vala ../src/Widgets/info-page.vala ../src/Widgets/play-bar.vala ../src/Widgets/song-entry.vala
FAILED: com.fyralabs.Victrola.p/src/application.c com.fyralabs.Victrola.p/src/main.c com.fyralabs.Victrola.p/src/window.c com.fyralabs.Victrola.p/src/Utils/async-task.c com.fyralabs.Victrola.p/src/Utils/gst-player.c com.fyralabs.Victrola.p/src/Utils/mpris.c com.fyralabs.Victrola.p/src/Utils/song-store.c com.fyralabs.Victrola.p/src/Utils/tag-parser.c com.fyralabs.Victrola.p/src/Widgets/info-page.c com.fyralabs.Victrola.p/src/Widgets/play-bar.c com.fyralabs.Victrola.p/src/Widgets/song-entry.c 
valac -C --debug --debug --gresourcesdir /home/jaiden/Documents/Projects/victrola/_build/data --define=HAS_TAGLIB_C --pkg taglib_c --pkg libbismuth-1 --pkg libhelium-1 --pkg gee-0.8 --pkg gtk4 --pkg gstreamer-tag-1.0 --pkg gstreamer-1.0 --color=always --directory com.fyralabs.Victrola.p --basedir ../ --gresources=../data/app.gresource.xml /home/jaiden/Documents/Projects/victrola/src/Utils/config.vapi /home/jaiden/Documents/Projects/victrola/src/Utils/gst-ext.vapi ../src/application.vala ../src/main.vala ../src/window.vala ../src/Utils/async-task.vala ../src/Utils/gst-player.vala ../src/Utils/mpris.vala ../src/Utils/song-store.vala ../src/Utils/tag-parser.vala ../src/Widgets/info-page.vala ../src/Widgets/play-bar.vala ../src/Widgets/song-entry.vala
../src/window.vala:107.35-107.55: warning: `Gtk.FileChooserNative' has been deprecated since 4.10
  107 |                 var chooser = new Gtk.FileChooserNative (null, this,
      |                                   ^~~~~~~~~~~~~~~~~~~~~             
../src/window.vala:107.21-107.27: warning: `Gtk.FileChooserNative' has been deprecated since 4.10
  107 |                 var chooser = new Gtk.FileChooserNative (null, this,
      |                     ^~~~~~~                                         
../src/window.vala:140.17-140.26: error: The name `child' does not exist in the context of `GLib.Object' (gobject-2.0)
  140 |                 item.child = new SongEntry ();
      |                 ^~~~~~~~~~                    
../src/window.vala:139.37-139.40: note: `item' was declared here
  139 |             factory.setup.connect ((item) => {
      |                                     ^~~~      
../src/window.vala:142.35-142.46: error: Argument 1: Cannot convert from `async void Victrola.MainWindow.on_bind_item (Gtk.ListItem)' to `delegate void Gtk.SignalListItemFactory.bind (Gtk.SignalListItemFactory, GLib.Object)'
  142 |             factory.bind.connect (on_bind_item);
      |                                   ^~~~~~~~~~~~  
../src/window.vala:155.17-155.26: error: The name `child' does not exist in the context of `GLib.Object' (gobject-2.0)
  155 |                 item.child = new SongEntry ();
      |                 ^~~~~~~~~~                    
../src/window.vala:154.38-154.41: note: `item' was declared here
  154 |             factory2.setup.connect ((item) => {
      |                                      ^~~~      
../src/window.vala:157.36-157.47: error: Argument 1: Cannot convert from `async void Victrola.MainWindow.on_bind_item (Gtk.ListItem)' to `delegate void Gtk.SignalListItemFactory.bind (Gtk.SignalListItemFactory, GLib.Object)'
  157 |             factory2.bind.connect (on_bind_item);
      |                                    ^~~~~~~~~~~~  
../src/window.vala:170.17-170.26: error: The name `child' does not exist in the context of `GLib.Object' (gobject-2.0)
  170 |                 item.child = new SongEntry ();
      |                 ^~~~~~~~~~                    
../src/window.vala:169.38-169.41: note: `item' was declared here
  169 |             factory3.setup.connect ((item) => {
      |                                      ^~~~      
../src/window.vala:172.36-172.47: error: Argument 1: Cannot convert from `async void Victrola.MainWindow.on_bind_item (Gtk.ListItem)' to `delegate void Gtk.SignalListItemFactory.bind (Gtk.SignalListItemFactory, GLib.Object)'
  172 |             factory3.bind.connect (on_bind_item);
      |                                    ^~~~~~~~~~~~  
Compilation failed: 6 error(s), 2 warning(s)
ninja: build stopped: subcommand failed.

jaiden on meowmachine victrola/_build on  main via C v13.2.1-gcc 
❯
```

### Hardware Info

![image](https://github.com/tau-OS/victrola/assets/37665485/5f94bf12-a89a-4f63-8f28-fe4ca7071fff)
